{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9515): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ef033e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Customer doesn't fill the first name","uid":"44ada2f1b2ef6a6e","parentUid":"18d095e1d3939efb34ef0995ddcca024","status":"broken","time":{"start":1688587943776,"stop":1688587943776,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"18d095e1d3939efb34ef0995ddcca024"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}